// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/AntonioMartinezLopez/enginsight/server/internal/domain/counter"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCounterStore creates a new instance of MockCounterStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCounterStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCounterStore {
	mock := &MockCounterStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCounterStore is an autogenerated mock type for the CounterStore type
type MockCounterStore struct {
	mock.Mock
}

type MockCounterStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCounterStore) EXPECT() *MockCounterStore_Expecter {
	return &MockCounterStore_Expecter{mock: &_m.Mock}
}

// GetMessageCount provides a mock function for the type MockCounterStore
func (_mock *MockCounterStore) GetMessageCount(ctx context.Context) (counter.Count, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageCount")
	}

	var r0 counter.Count
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (counter.Count, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) counter.Count); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(counter.Count)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCounterStore_GetMessageCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageCount'
type MockCounterStore_GetMessageCount_Call struct {
	*mock.Call
}

// GetMessageCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCounterStore_Expecter) GetMessageCount(ctx interface{}) *MockCounterStore_GetMessageCount_Call {
	return &MockCounterStore_GetMessageCount_Call{Call: _e.mock.On("GetMessageCount", ctx)}
}

func (_c *MockCounterStore_GetMessageCount_Call) Run(run func(ctx context.Context)) *MockCounterStore_GetMessageCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCounterStore_GetMessageCount_Call) Return(count counter.Count, err error) *MockCounterStore_GetMessageCount_Call {
	_c.Call.Return(count, err)
	return _c
}

func (_c *MockCounterStore_GetMessageCount_Call) RunAndReturn(run func(ctx context.Context) (counter.Count, error)) *MockCounterStore_GetMessageCount_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function for the type MockCounterStore
func (_mock *MockCounterStore) Increment(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCounterStore_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type MockCounterStore_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCounterStore_Expecter) Increment(ctx interface{}) *MockCounterStore_Increment_Call {
	return &MockCounterStore_Increment_Call{Call: _e.mock.On("Increment", ctx)}
}

func (_c *MockCounterStore_Increment_Call) Run(run func(ctx context.Context)) *MockCounterStore_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCounterStore_Increment_Call) Return(err error) *MockCounterStore_Increment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCounterStore_Increment_Call) RunAndReturn(run func(ctx context.Context) error) *MockCounterStore_Increment_Call {
	_c.Call.Return(run)
	return _c
}
