// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/AntonioMartinezLopez/enginsight/server/internal/domain/counter"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCounter creates a new instance of MockCounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCounter {
	mock := &MockCounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCounter is an autogenerated mock type for the Counter type
type MockCounter struct {
	mock.Mock
}

type MockCounter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCounter) EXPECT() *MockCounter_Expecter {
	return &MockCounter_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockCounter
func (_mock *MockCounter) Count(ctx context.Context, message string) (int, error) {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, message)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, message)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCounter_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockCounter_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
func (_e *MockCounter_Expecter) Count(ctx interface{}, message interface{}) *MockCounter_Count_Call {
	return &MockCounter_Count_Call{Call: _e.mock.On("Count", ctx, message)}
}

func (_c *MockCounter_Count_Call) Run(run func(ctx context.Context, message string)) *MockCounter_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCounter_Count_Call) Return(n int, err error) *MockCounter_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCounter_Count_Call) RunAndReturn(run func(ctx context.Context, message string) (int, error)) *MockCounter_Count_Call {
	_c.Call.Return(run)
	return _c
}

// GetNumberOfProcessedMessages provides a mock function for the type MockCounter
func (_mock *MockCounter) GetNumberOfProcessedMessages(ctx context.Context) (counter.Count, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetNumberOfProcessedMessages")
	}

	var r0 counter.Count
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (counter.Count, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) counter.Count); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(counter.Count)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCounter_GetNumberOfProcessedMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNumberOfProcessedMessages'
type MockCounter_GetNumberOfProcessedMessages_Call struct {
	*mock.Call
}

// GetNumberOfProcessedMessages is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCounter_Expecter) GetNumberOfProcessedMessages(ctx interface{}) *MockCounter_GetNumberOfProcessedMessages_Call {
	return &MockCounter_GetNumberOfProcessedMessages_Call{Call: _e.mock.On("GetNumberOfProcessedMessages", ctx)}
}

func (_c *MockCounter_GetNumberOfProcessedMessages_Call) Run(run func(ctx context.Context)) *MockCounter_GetNumberOfProcessedMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCounter_GetNumberOfProcessedMessages_Call) Return(count counter.Count, err error) *MockCounter_GetNumberOfProcessedMessages_Call {
	_c.Call.Return(count, err)
	return _c
}

func (_c *MockCounter_GetNumberOfProcessedMessages_Call) RunAndReturn(run func(ctx context.Context) (counter.Count, error)) *MockCounter_GetNumberOfProcessedMessages_Call {
	_c.Call.Return(run)
	return _c
}
